/**
 * @file docxService.ts
 * @description Service for generating and downloading Microsoft Word (.docx) documents 
 * from the generated didactic sequences. Uses the 'docx' and 'file-saver' libraries.
 */

import { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, WidthType, BorderStyle, HeadingLevel, AlignmentType } from "docx";
import { saveAs } from "file-saver";
import { DidacticSequence, SequenceInput } from "../types";

/**
 * Generates a formal .docx document based on the AI response.
 * Includes tables for general info, activities, and rubrics.
 * 
 * @param data The didactic sequence generated by the AI
 * @param input The original user inputs for context
 */
export const generateDocx = async (data: DidacticSequence, input: SequenceInput) => {

  /**
    * Internal helper to create a consistent two-column row for tables.
    * @param label Left column text (bold)
    * @param value Right column text
    */
  const createRow = (label: string, value: string) => {
    return new TableRow({
      children: [
        new TableCell({
          width: { size: 30, type: WidthType.PERCENTAGE },
          children: [new Paragraph({ children: [new TextRun({ text: label, bold: true })] })],
        }),
        new TableCell({
          width: { size: 70, type: WidthType.PERCENTAGE },
          children: [new Paragraph({ children: [new TextRun(value || "")] })],
        }),
      ],
    });
  };

  // --- Activities Table Processing ---
  const activitiesRows = data.actividades.flatMap((act) => [
    new TableRow({
      children: [
        new TableCell({
          columnSpan: 2,
          children: [
            new Paragraph({
              children: [new TextRun({ text: `Sesión ${act.sesion} (${act.tiempo})`, bold: true })],
              alignment: AlignmentType.CENTER,
            }),
          ],
        }),
      ],
    }),
    createRow("Descripción", act.descripcion),
    createRow("Materiales", act.materiales.join(", ")),
    createRow("Imprimibles", act.imprimibles),
  ]);

  // --- Rubric Table Processing ---
  const rubricRows = [
    new TableRow({
      children: [
        new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Criterio", bold: true })] })] }),
        new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Básico", bold: true })] })] }),
        new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Satisfactorio", bold: true })] })] }),
        new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Avanzado", bold: true })] })] }),
      ]
    }),
    ...data.rubrica.map(r => new TableRow({
      children: [
        new TableCell({ children: [new Paragraph(r.criterio)] }),
        new TableCell({ children: [new Paragraph(r.basico)] }),
        new TableCell({ children: [new Paragraph(r.satisfactorio)] }),
        new TableCell({ children: [new Paragraph(r.avanzado)] }),
      ]
    }))
  ];

  // --- Document Assembly ---
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          // Header
          new Paragraph({
            text: "INSTITUCIÓN EDUCATIVA GUAIMARAL",
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: "FORMATO DE SECUENCIA DIDÁCTICA",
            heading: HeadingLevel.HEADING_2,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({ text: "" }), // Spacer

          // Administrative Info Table
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              createRow("Grado", input.grado),
              createRow("Área", input.area),
              createRow("Tema", input.tema),
              createRow("DBA", data.dba_utilizado || input.dba),
              createRow("Eje CRESE", input.ejeCrese),
              createRow("Objetivo de Aprendizaje", data.objetivo_aprendizaje),
              createRow("Estándar", data.estandar),
              createRow("Competencias MEN", data.competencias_men),
              createRow("Metodología", data.metodologia),
              createRow("Corporiedad (ADI)", data.corporiedad_adi),
              createRow("Productos Asociados", data.productos_asociados),
              createRow("Instrumentos de Evaluación", data.instrumentos_evaluacion),
              createRow("Adecuaciones PIAR", data.adecuaciones_piar),
              createRow("Bibliografía", data.bibliografia),
              createRow("Observaciones", data.observaciones),
            ],
          }),

          new Paragraph({ text: "" }),
          new Paragraph({ text: "ACTIVIDADES DETALLADAS", heading: HeadingLevel.HEADING_3 }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: activitiesRows,
          }),

          new Paragraph({ text: "" }),
          new Paragraph({ text: "RÚBRICA DE EVALUACIÓN", heading: HeadingLevel.HEADING_3 }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: rubricRows
          }),

          new Paragraph({ text: "" }),
          new Paragraph({ text: "TALLER / EVALUACIÓN", heading: HeadingLevel.HEADING_3 }),
          ...data.evaluacion.map((item, i) => new Paragraph({
            text: `${i + 1}. ${item.pregunta}`,
            spacing: { after: 200 }
          })),

          new Paragraph({ text: "" }),
          new Paragraph({ text: "TALLER DE APLICACIÓN", heading: HeadingLevel.HEADING_3 }),
          new Paragraph({ children: [new TextRun({ text: data.taller_imprimible.introduccion, italics: true })] }),
          new Paragraph({ children: [new TextRun({ text: "Instrucciones:", bold: true })] }),
          new Paragraph({ text: data.taller_imprimible.instrucciones }),
          new Paragraph({ children: [new TextRun({ text: "Ejercicios:", bold: true })] }),
          ...data.taller_imprimible.ejercicios.map((ej, i) => new Paragraph({
            children: [new TextRun(`${i + 1}. ${ej}`)],
            spacing: { before: 200 }
          })),
          new Paragraph({ text: "" }),
          new Paragraph({ children: [new TextRun({ text: "RETO CREATIVO:", bold: true })] }),
          new Paragraph({ children: [new TextRun({ text: data.taller_imprimible.reto_creativo, italics: true })] }),

          new Paragraph({ text: "" }),
          new Paragraph({ text: "RECURSOS", heading: HeadingLevel.HEADING_3 }),
          ...data.recursos.map(r => new Paragraph({
            children: [
              new TextRun({ text: `• ${r.nombre}: `, bold: true }),
              new TextRun(r.descripcion)
            ]
          }))
        ],
      },
    ],
  });

  // Pack and Save
  const blob = await Packer.toBlob(doc);
  const fileName = `Secuencia_${input.tema.replace(/\s+/g, '_')}_${input.grado.replace(/\s+/g, '_')}.docx`;
  saveAs(blob, fileName);
};

