/**
 * @file docxService.ts
 * @description Service for generating and downloading Microsoft Word (.docx) documents 
 * from the generated didactic sequences. Uses the 'docx' and 'file-saver' libraries.
 */

import { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, WidthType, HeadingLevel, AlignmentType } from "docx";
import { saveAs } from "file-saver";
import { DidacticSequence, SequenceInput } from "../types";

/**
 * Generates a formal .docx document based on the AI response.
 * Follows the institutional format of Francisco de Paula Santander.
 * 
 * @param data The didactic sequence generated by the AI
 * @param input The original user inputs for context
 */
export const generateDocx = async (data: DidacticSequence, input: SequenceInput) => {

  /**
    * Internal helper to create a consistent two-column row for tables.
    * @param label Left column text (bold)
    * @param value Right column text
    */
  const createRow = (label: string, value: string) => {
    return new TableRow({
      children: [
        new TableCell({
          width: { size: 30, type: WidthType.PERCENTAGE },
          children: [new Paragraph({ children: [new TextRun({ text: label, bold: true })] })],
        }),
        new TableCell({
          width: { size: 70, type: WidthType.PERCENTAGE },
          children: [new Paragraph({ children: [new TextRun(value || "")] })],
        }),
      ],
    });
  };

  /**
   * Helper for section headers within the table
   */
  const createSectionHeader = (text: string) => {
    return new TableRow({
      children: [
        new TableCell({
          columnSpan: 2,
          shading: { fill: "D6E4F0" },
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [new TextRun({ text, bold: true, size: 24 })],
            }),
          ],
        }),
      ],
    });
  };

  // --- Sesiones Detalle rows ---
  const sesionesRows: TableRow[] = [];
  if (data.sesiones_detalle && data.sesiones_detalle.length > 0) {
    sesionesRows.push(createSectionHeader("5. PLAN DETALLADO POR SESIÓN"));
    data.sesiones_detalle.forEach((sesion) => {
      sesionesRows.push(
        new TableRow({
          children: [
            new TableCell({
              width: { size: 25, type: WidthType.PERCENTAGE },
              shading: { fill: "EBF5FB" },
              children: [new Paragraph({
                children: [new TextRun({
                  text: `Sesión ${sesion.numero}: ${sesion.titulo}`,
                  bold: true,
                  size: 20
                })]
              })]
            }),
            new TableCell({
              width: { size: 75, type: WidthType.PERCENTAGE },
              children: [new Paragraph({ children: [new TextRun(sesion.descripcion || "")] })]
            })
          ]
        })
      );
    });
  }

  // --- Recursos Links rows ---
  const recursosLinksRows: TableRow[] = [];
  if (data.recursos_links && data.recursos_links.length > 0) {
    recursosLinksRows.push(createSectionHeader("8. RECURSOS DIGITALES CON LINKS"));
    data.recursos_links.forEach((recurso) => {
      recursosLinksRows.push(
        new TableRow({
          children: [
            new TableCell({
              width: { size: 20, type: WidthType.PERCENTAGE },
              shading: { fill: "E9F7EF" },
              children: [new Paragraph({
                children: [new TextRun({ text: recurso.tipo, bold: true, size: 18 })]
              })]
            }),
            new TableCell({
              width: { size: 35, type: WidthType.PERCENTAGE },
              children: [new Paragraph({ children: [new TextRun({ text: recurso.nombre, bold: true })] })]
            }),
            new TableCell({
              width: { size: 45, type: WidthType.PERCENTAGE },
              children: [new Paragraph({ children: [new TextRun({ text: recurso.url, color: "1155CC" })] })]
            })
          ]
        })
      );
    });
  }

  // --- Document Assembly ---
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          // Header
          new Paragraph({
            text: "INSTITUCIÓN EDUCATIVA TÉCNICA FRANCISCO DE PAULA SANTANDER DE GALAPA",
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: "PLANEACIÓN DE CLASE",
            heading: HeadingLevel.HEADING_2,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({ text: "" }), // Spacer

          // Main Planning Table
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              // General Info
              createRow("DOCENTE", data.nombre_docente),
              createRow("ÁREA", data.area),
              createRow("ASIGNATURA", data.asignatura),
              createRow("GRADO", data.grado),
              createRow("GRUPOS", data.grupos),
              createRow("FECHA", data.fecha),

              // Purpose
              createSectionHeader("1. PROPÓSITO"),
              new TableRow({
                children: [
                  new TableCell({
                    columnSpan: 2,
                    children: [new Paragraph(data.proposito)],
                  }),
                ],
              }),

              // Indicators
              createSectionHeader("2. INDICADORES"),
              createRow("COGNITIVO", data.indicadores.cognitivo),
              createRow("AFECTIVO", data.indicadores.afectivo),
              createRow("EXPRESIVO", data.indicadores.expresivo),

              // Teachings
              createSectionHeader("3. ENSEÑANZAS"),
              new TableRow({
                children: [
                  new TableCell({
                    columnSpan: 2,
                    children: data.ensenanzas.map(e => new Paragraph({ text: `• ${e}` })),
                  }),
                ],
              }),

              // Didactic Sequence
              createSectionHeader("4. SECUENCIA DIDÁCTICA (Resumen)"),
              createRow("MOTIVACIÓN Y ENCUADRE", data.secuencia_didactica.motivacion_encuadre),
              createRow("ENUNCIACIÓN", data.secuencia_didactica.enunciacion),
              createRow("MODELACIÓN", data.secuencia_didactica.modelacion),
              createRow("SIMULACIÓN", data.secuencia_didactica.simulacion),
              createRow("EJERCITACIÓN", data.secuencia_didactica.ejercitacion),
              createRow("DEMOSTRACIÓN", data.secuencia_didactica.demostracion),

              // Sesiones detalle (NUEVO)
              ...sesionesRows,

              // Didactics
              createSectionHeader("6. DIDÁCTICA"),
              new TableRow({
                children: [
                  new TableCell({
                    columnSpan: 2,
                    children: [new Paragraph(data.didactica)],
                  }),
                ],
              }),

              // Resources
              createSectionHeader("7. RECURSOS"),
              new TableRow({
                children: [
                  new TableCell({
                    columnSpan: 2,
                    children: [new Paragraph(data.recursos)],
                  }),
                ],
              }),

              // Recursos con links (NUEVO)
              ...recursosLinksRows,
            ],
          }),

          new Paragraph({ text: "" }),

          // Signatures Table
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "ELABORÓ:", bold: true }), new TextRun(` ${data.elaboro}`)] })] }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "REVISÓ:", bold: true }), new TextRun(` ${data.reviso}`)] })] }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "FECHA:", bold: true }), new TextRun(` ${data.pie_fecha}`)] })] }),
                ]
              })
            ]
          }),

          // Annex: Taller Imprimible
          new Paragraph({ text: "", pageBreakBefore: true }),
          new Paragraph({
            text: "TALLER DE APLICACIÓN",
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({ text: "Francisco de Paula Santander - Galapa", alignment: AlignmentType.CENTER }),
          new Paragraph({ text: "" }),
          new Paragraph({ children: [new TextRun({ text: "Nombre: _________________________________________________", bold: true })] }),
          new Paragraph({ text: "" }),

          ...(data.taller_imprimible ? [
            new Paragraph({ children: [new TextRun({ text: "INTRODUCCIÓN:", bold: true, underline: {} })] }),
            new Paragraph({ children: [new TextRun({ text: data.taller_imprimible.introduccion, italics: true })] }),
            new Paragraph({ text: "" }),

            new Paragraph({ children: [new TextRun({ text: "INSTRUCCIONES:", bold: true, underline: {} })] }),
            new Paragraph({ text: data.taller_imprimible.instrucciones }),
            new Paragraph({ text: "" }),

            new Paragraph({ children: [new TextRun({ text: "ACTIVIDADES:", bold: true, underline: {} })] }),
            ...data.taller_imprimible.ejercicios.map((ej, i) => new Paragraph({
              text: `${i + 1}. ${ej}`,
              spacing: { before: 200, after: 400 }
            })),

            new Paragraph({ text: "" }),
            new Paragraph({
              shading: { fill: "F9F9F9" },
              children: [
                new TextRun({ text: "RETO CREATIVO: ", bold: true }),
                new TextRun({ text: data.taller_imprimible.reto_creativo, italics: true })
              ]
            })
          ] : []),

          // ============================================================
          // BANCO DE PREGUNTAS POR COMPETENCIAS (NUEVO - en nueva página)
          // ============================================================
          new Paragraph({ text: "", pageBreakBefore: true }),
          new Paragraph({
            text: "EVALUACIÓN POR COMPETENCIAS — 10 PREGUNTAS TIPO ICFES",
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({ text: "Francisco de Paula Santander - Galapa", alignment: AlignmentType.CENTER }),
          new Paragraph({ text: "" }),
          new Paragraph({
            children: [
              new TextRun({ text: "Nombre: ____________________________________________  ", bold: true }),
              new TextRun({ text: "Grado: _______ Grupo: _______  ", bold: true }),
              new TextRun({ text: "Fecha: _______________", bold: true })
            ]
          }),
          new Paragraph({ text: "" }),

          ...data.evaluacion.map((ev, i) => [
            // Competencia badge
            new Paragraph({
              shading: { fill: "D6E4F0" },
              children: [
                new TextRun({ text: `Competencia: ${ev.competencia || 'Interpretativa'}`, bold: true, size: 18, color: "1A5276" })
              ]
            }),
            // Pregunta
            new Paragraph({
              children: [new TextRun({ text: `${i + 1}. ${ev.pregunta}`, bold: true })],
              spacing: { before: 120 }
            }),
            // Opciones de respuesta
            ...(ev.opciones || []).map((opt, j) => new Paragraph({
              text: `${String.fromCharCode(65 + j)}) ${opt}`,
              indent: { left: 720 },
              spacing: { after: 80 }
            })),
            new Paragraph({ text: "" })
          ]).flat()
        ],
      },
    ],
  });

  // Pack and Save
  const blob = await Packer.toBlob(doc);
  const fileName = `Planeacion_${data.titulo_secuencia.replace(/\s+/g, '_')}_${data.grado.replace(/\s+/g, '_')}.docx`;
  saveAs(blob, fileName);
};
